import { world } from "@minecraft/server";
import { ModalFormData } from "@minecraft/server-ui";
world.afterEvents.itemUse.subscribe((event) => {
    if (event.itemStack.typeId == "minecraft:stick") {
        new ModalFormData()
            .title("watts.shop.15.40")
            .submitButton("구매")
            .slider("d000100apple", 0, 64)
            .label("textures/items/apple")
            .slider("d000001bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000002bamboo", 0, 64)
            .label("textures/items/amethyst_shard")
            .slider("d000003amethyst_shard", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000004bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000005bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000006bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000007bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000008bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000009bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000010bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000011bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000012bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000013bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000014bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000015bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000016bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000017bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000018bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000019bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000020bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000021bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000022bamboo", 0, 64)
            .label("textures/items/bamboo")
            .slider("d000023bamboo", 0, 64)
            .label("textures/items/bamboo")
            .show(event.source);
    }
    if (event.itemStack.typeId == "minecraft:blaze_rod") {
        new ModalFormData()
            .title("test")
            .label("Hello World")
            .show(event.source);
    }
});
